exclude: ^.idea/
repos:
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    -   id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports' ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        args: ['--style=.style.yapf', '--parallel', '--in-place']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports, --python-version=3.6, --show-error-codes, --allow-untyped-decorators]
        additional_dependencies:
            - numpy>=1.19.2
            - pyspark>=2.4.0
            - logger
            - sparkautomapper>=0.1.27
