version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    volumes:
      - ./:/SparkpipelineFramework/
    container_name: spf_dev
    working_dir: /SparkpipelineFramework
