version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    volumes:
      - ./:/SparkpipelineFramework/
#      - ../SparkAutoMapper/spark_auto_mapper:/opt/project/spark_auto_mapper
    container_name: spf_dev
    working_dir: /SparkpipelineFramework
