version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    volumes:
      - ./:/SparkpipelineFramework/
    container_name: helix_client
    working_dir: /SparkpipelineFramework

  spark:
    user: root
    image: sparkpipelineframework_dev:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_LOCAL_IP=spark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/bitnami/spark/bin/spark-submit --master spark://spark:7077 /opt/bitnami/spark/examples/src/main/python/pi.py 10"]
        timeout: 300s
        retries: 5
        start_period: 60s

  spark-worker:
    user: root
    image: sparkpipelineframework_dev:latest
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark
      - SPARK_PUBLIC_DNS=localhost
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/bitnami/spark/bin/spark-submit --master spark://spark:7077 /opt/bitnami/spark/examples/src/main/python/pi.py 10"]
        interval: 300s
        timeout: 300s
