name: Build and Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: pre-commit
        run: make run-pre-commit

      # setup and install everything and run tests
      - name: up
        run: make up

      - name: Create reports output folder
        run: mkdir -p /home/runner/work/${{ github.repository }}/reports

      - name: tests
        run: docker compose run --rm --name spf_tests -v /home/runner/work/${{ github.repository }}/reports:/reports dev pytest tests spark_pipeline_framework --junitxml=/reports/test-results.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: /home/runner/work/${{ github.repository }}/reports/**/*.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
