# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Sync Pipfile with setup.py
      run: |
        python -m pip install --no-cache-dir pipenv
        pipenv sync --dev --system
        pipenv-setup sync --pipfile
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@master
    - name: Set release tag in VERSION
      uses: DamianReeves/write-file-action@master
      with:
        path: VERSION
        contents: |
          ${{ steps.previoustag.outputs.tag }}
        write-mode: overwrite
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
